const Router=require('koa-router')
const ArticleRouter=new Router({prefix:'/article'})
const controller=require('../controller/ArticleController')
const middle=require('../middleware/LoginMiddle')
ArticleRouter.get('/list',middle.verifyAuth,controller.list)
ArticleRouter.post('/delete',middle.verifyAuth,controller.deleteArticle)
ArticleRouter.post('/hide',middle.verifyAuth,controller.hideArticle)
ArticleRouter.post('/add',middle.verifyAuth,controller.addArticle)
ArticleRouter.get('/detail',middle.verifyAuth,controller.detail)
ArticleRouter.post('/edit',middle.verifyAuth,controller.edit)
module.exports=ArticleRouter