const Router=require('koa-router')
const SchoolRouter=new Router({prefix:'/school'})
const controller=require('../controller/SchoolController')
const middle=require('../middleware/SchoolMiddle')
const {verifyAuth}=require('../middleware/LoginMiddle')
SchoolRouter.get('/list',verifyAuth,controller.list)
SchoolRouter.post('/delete',verifyAuth,controller.deleteUser)
SchoolRouter.post('/add',verifyAuth,middle.verifyAddSchool,controller.add)
SchoolRouter.get('/detail',verifyAuth,controller.detail)
SchoolRouter.post('/edit',verifyAuth,middle.verifyEditSchool,controller.edit)
module.exports=SchoolRouter